### ISSUE TITLE
Square brackets test pushes "blue" away from context start

### ISSUE THREAD

**Issue by lopho** [JohannesGaessler/stable-diffusion-tools#1]
The results of these tests are skewed by the insertion of tokens between red and blue. Not by the brackets themselves.
I have done tentative tests, with alternating [red],blue | blue, [red] | [[red]], blue | blue, [[red]] ...
and the tentative results are flat within error.
Until I (or you) can run a longer experiment, I would suggest adding a disclaimer to your findings.

**Comment by JohannesGaessler** [comment]
Thanks for bringing this to my attention.
I've re-run the analysis with "red" at the end of prompt rather than the middle.
There does not seem to be a consistent effect.
Please confirm whether you agree with what I've written in the updated readme file.

**Comment by lopho** [comment]
Yes, I'd say that is agreeable.
